### ISSUE TITLE
React StrictMode breaks sdk

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#1641]
- Opening second tab using singleton results in assertion errors
- Reloading first tab using singleton also results in assertion errors

```
dxos:react-toolkit:error unhandledrejection +44ms AssertionError [ERR_ASSERTION]: undefined == true
at Stream._messageHandler (useBotFactoryClient.ts:82456:31)
at next (browser.js:8647:18)
at Stream._messageHandler (browser.js:8696:34)
at next (browser.js:8647:18)
at RequestItem.onResponse [as resolve] (rpc.ts:307:11)
at RpcPeer._receive (rpc.ts:192:12)
at rpc.ts:95:20
at handler (useBotFactoryClient.ts:96799:9)
```

**Comment by zhenyasav** [comment]
🥳
