### ISSUE TITLE
Telemetry errors

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3485]
**Describe the bug**
Console errors from telemetry (e.g., from halo.dxos.org)

**To Reproduce**
Load app and open devtools console.

**Expected behavior**
No errors

**Additional context**

```
index.mjs:759 unhandledrejection TypeError: Failed to fetch
    at instrument.js:138:1
    at httpclient.js:265:1
    at o (analytics.min.js:1:38434)
    at Object.dispatch (fetch-dispatcher.ts:14:18)
    at Object.<anonymous> (index.ts:126:12)
    at tslib.es6.js:103:23
    at Object.next (tslib.es6.js:108:37)
    at tslib.es6.js:80:8
    at new Promise (<anonymous>)
    at s (tslib.es6.js:72:27)
    at Object.c (index.ts:98:38)
    at delivery.js:28:10
    at delivery.js:11:33
    at tslib.es6.js:103:23
    at Object.next (tslib.es6.js:108:37)
    at tslib.es6.js:80:8
    at new Promise (<anonymous>)
    at s (tslib.es6.js:72:27)
    at delivery.js:4:36
    at o (delivery.js:27:41)
    at event-queue.js:324:46
    at Array.map (<anonymous>)
    at n.<anonymous> (event-queue.js:323:67)
    at tslib.es6.js:103:23
    at Object.next (tslib.es6.js:108:37)
    at u (tslib.es6.js:73:86)
(anonymous) @ instrument.js:109
(anonymous) @ captureconsole.js:73
logError @ index.mjs:759
(anonymous) @ index.mjs:772
Show 2 more frames
index.mjs:759 unhandledrejection 
(anonymous) @ instrument.js:109
(anonymous) @ captureconsole.js:73
logError @ index.mjs:759
(anonymous) @ index.mjs:772
Show 2 more frames
3index.mjs:759 unhandledrejection 
(anonymous) @ instrument.js:109
(anonymous) @ captureconsole.js:73
logError @ index.mjs:759
(anonymous) @ index.mjs:772
Show 2 more frames
index.mjs:11346 Error: Timeout [200ms]
    at asyncTimeout (index.mjs:62:1)
    at RpcPeer.call (index.mjs:352:1)
    at Object.call (index.mjs:566:1)
    at Service.stop (index.mjs:571:1)
    at IFrameProxyRuntime.close (chunk-KN2NX2RP.mjs:3447:1)
```

**Comment by zhenyasav** [comment]
this is due to duck duck go privacy extension in the browser
