### ISSUE TITLE
Agent stability issue

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3694]
- [x] Check functions plugin is registered and warn when invoked
- [x] Check errors when stopping agents

```
chadfowler.eth: /Users/chadfowler/src/dxos/packages/common/async/src/timeout.ts:38
  const throwable = (err === undefined || typeof err === 'string') ? new TimeoutError(timeout, err) : err;
                                                                     ^
TimeoutError: Timeout [3000ms]
    at asyncTimeout (/Users/chadfowler/src/dxos/packages/common/async/src/timeout.ts:38:70)
    at RpcPeer.call (/Users/chadfowler/src/dxos/packages/core/mesh/rpc/src/rpc.ts:375:23)
    at Object.call (/Users/chadfowler/src/dxos/packages/core/mesh/rpc/src/service.ts:127:39)
    at Service.write (/Users/chadfowler/src/dxos/packages/common/codec-protobuf/src/service.ts:85:42)
    at DatabaseProxy.commitBatch (/Users/chadfowler/src/dxos/packages/core/echo/echo-db/src/packlets/database/database-proxy.ts:236:8)
    at TypedObjectImpl._inBatch (/Users/chadfowler/src/dxos/packages/core/echo/echo-schema/src/typed-object.ts:309:35)
    at TypedObjectImpl._set (/Users/chadfowler/src/dxos/packages/core/echo/echo-schema/src/typed-object.ts:261:10)
    at Object.set (/Users/chadfowler/src/dxos/packages/core/echo/echo-schema/src/typed-object.ts:374:14)
    at Timeout._onTimeout (/Users/chadfowler/src/dxos/packages/experimental/kai-functions/src/functions/chess.ts:37:21)
    at runNextTicks (node:internal/process/task_queues:60:5)
[5:39 PM]chadfowler.eth: I got Tuple set up
[4:48 PM]chadfowler.eth: I guess I should have taken notes so I would remember how we solved various problems....
[4:48 PM]chadfowler.eth: $ dx function dev-server  --verbose
TypeError: Cannot read properties of undefined (reading 'register')
[4:49 PM]chadfowler.eth: ooh i bet i know.  i created a new DX_PROFILE because i couldn't figure out how to clear my halo
[4:49 PM]richburdon: add agents: functions: port: 7001 to config
[4:49 PM]chadfowler.eth: and i bet i need a config
[4:51 PM]chadfowler.eth: sadly that didn't do it.  Not wanting to drag you into troubleshooting mode now though.
[4:53 PM]richburdon: dx reset --force should clear your halo
[4:53 PM]chadfowler.eth: wonderful thx
[4:53 PM]richburdon: but to fix the issue -- above it should be "agent" not "agents"
[4:54 PM]chadfowler.eth: i copied what we had in the other config
[4:54 PM]richburdon: and you till get the register issue? did you restart the agent?
[4:54 PM]chadfowler.eth: nope.  will try that
[4:55 PM]chadfowler.eth: dx agent stop isn't stopping the agent
[4:55 PM]chadfowler.eth: dx agent stop && dx agent start
forever-daemon.ts:147 INFO stopped { profile: 'local-testing' }
Agent stopped
client.ts:77 ERROR connect ECONNREFUSED /tmp/dx/run/profile/local-testing/agent.sock { url: 'ws+unix:///tmp/dx/run/profile/local-testing/agent.sock' }
(node:76885) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
Error: listen EADDRINUSE: address already in use :::7001
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (/Users/chadfowler/src/dxos/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/application.js:618:24)
    at FunctionsPlugin.open (/Users/chadfowler/src/dxos/packages/core/agent/src/plugins/functions/functions-plugin.ts:66:18)
    at Agent.start (/Users/chadfowler/src/dxos/packages/core/agent/src/agent.ts:101:20)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at processTimers (node:internal/timers:512:7)
    at async Start._runInForeground (/Users/chadfowler/src/dxos/packages/devtools/cli/src/commands/agent/start.ts:89:5) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 7001
}

Failed to start daemon: Error: connect ECONNREFUSED /tmp/dx/run/profile/local-testing/agent.sock
[4:55 PM]chadfowler.eth: dx agent stop
Agent stopped
[4:55 PM]chadfowler.eth: dx agent list
 profile       process uptime
 ───────────── ─────── ──────────────────
 default       73209   27 minutes
 local-testing 76884   less than a minute
[4:56 PM]chadfowler.eth: first one gave me the error you see
[4:56 PM]chadfowler.eth: then it just acts as if it worked but the process is still there
[4:56 PM]richburdon: can you try dx reset --force --verbose and see if it shows you the files and socket
[4:57 PM]richburdon: then stry stop again
[4:57 PM]richburdon: and if that doesn't work try to kill the process
[4:57 PM]richburdon: is this CLI from src in main?
[4:57 PM]chadfowler.eth: ya though i haven't recompiled it since yesterday
```

**Comment by mykola-vrmchk** [comment]
getting the same error
```bash
>dx function dev-server  --verbose
dev-server.ts:63 ERROR parsing function (check functions.yml manifest) {
  error: "Error: Cannot find module '/Users/mykola/Documents/dev/dxos/packages/experimental/kai-functions/src/functions/chess'\n" +
    'Require stack:\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@dxos/functions/dist/lib/node/index.cjs\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/module-loader.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/util.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/formatter.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/command.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/flags.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/styled/table.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/styled/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/command.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/bin/run\n' +
    '    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:841:27)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1061:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:103:18)\n' +
    '    at DevServer.initialize (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@dxos/functions/dist/lib/node/index.cjs:64:25)\n' +
    '    at /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js:32:26\n' +
    '    at Dev.execWithClient (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/base-command.js:260:29)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Dev.run (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js:26:9)\n' +
    '    at async Dev._run (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/command.js:117:22)'
}
dev-server.ts:63 ERROR parsing function (check functions.yml manifest) {
  error: "Error: Cannot find module '/Users/mykola/Documents/dev/dxos/packages/experimental/kai-functions/src/functions/chatgpt'\n" +
    'Require stack:\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@dxos/functions/dist/lib/node/index.cjs\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/module-loader.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/util.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/formatter.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/command.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/flags.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/styled/table.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/styled/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/command.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/bin/run\n' +
    '    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:841:27)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1061:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:103:18)\n' +
    '    at DevServer.initialize (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@dxos/functions/dist/lib/node/index.cjs:64:25)\n' +
    '    at /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js:32:26\n' +
    '    at Dev.execWithClient (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/base-command.js:260:29)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Dev.run (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js:26:9)\n' +
    '    at async Dev._run (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/command.js:117:22)'
}
dev-server.ts:63 ERROR parsing function (check functions.yml manifest) {
  error: "Error: Cannot find module '/Users/mykola/Documents/dev/dxos/packages/experimental/kai-functions/src/functions/hello'\n" +
    'Require stack:\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@dxos/functions/dist/lib/node/index.cjs\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/module-loader.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/util.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/formatter.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/command.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/help/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/flags.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/styled/table.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/styled/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/cli-ux/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/command.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/index.js\n' +
    '- /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/bin/run\n' +
    '    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:841:27)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1061:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:103:18)\n' +
    '    at DevServer.initialize (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@dxos/functions/dist/lib/node/index.cjs:64:25)\n' +
    '    at /Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js:32:26\n' +
    '    at Dev.execWithClient (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/base-command.js:260:29)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Dev.run (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/dist/src/commands/function/dev-server.js:26:9)\n' +
    '    at async Dev._run (/Users/mykola/.nvm/versions/node/v18.12.1/lib/node_modules/@dxos/cli/node_modules/@oclif/core/lib/command.js:117:22)'
}
    TypeError: Cannot read properties of undefined (reading 'register')```

**Comment by mykola-vrmchk** [comment]
Added warning in `./bin/dev` that says "Warning: Running CLI in dev mode (only for development purposes)."
