### ISSUE TITLE
Agent stale on exit (locking)

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4082]
- [x] fix error on `agent stop` https://github.com/dxos/dxos/pull/4089
```
packages/devtools/cli burdon/move-diagnostics-to-client-services ✗                    28m ⚑
▶ dx agent stop
Error: Agent may be stale (to restart: 'dx agent restart --force')

packages/devtools/cli burdon/move-diagnostics-to-client-services ✗                    29m ⚑
▶ dx agent restart --force
Error: Timeout waiting for agent.
    at ForeverDaemon.stop (/Users/burdon/Code/dxos/dxos/packages/core/agent/src/forever/forever-daemon.ts:182:14)
    at ForeverDaemon.restart (/Users/burdon/Code/dxos/dxos/packages/core/agent/src/forever/forever-daemon.ts:190:5)
    at /Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/commands/agent/restart.ts:32:29
    at Restart.execWithDaemon (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:358:23)
    at Restart.run (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/commands/agent/restart.ts:31:16)
    at Restart._run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_d2gyhxeuxd6tnmgqdyixls47tq/node_modules/@oclif/core/lib/command.js:117:22)
    at Config.runCommand (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_d2gyhxeuxd6tnmgqdyixls47tq/node_modules/@oclif/core/lib/config/config.js:329:25)
    at Object.run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_d2gyhxeuxd6tnmgqdyixls47tq/node_modules/@oclif/core/lib/main.js:89:16)
```

**Comment by mykola-vrmchk** [comment]
It is hard to repro, so I wrote a script to start a lot of agents and populate them with mutations, never experienced problems with stopping them

**Comment by mykola-vrmchk** [comment]
https://github.com/dxos/dxos/issues/4110 will solve it
