### ISSUE TITLE
App template troubleshooting

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4590]
1). The getting started docs may be out of date?

```zsh
Code/dxos/test
▶ npm init @dxos@latest

npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@dxos" of package "@dxos@latest/create": name can only contain URL-friendly characters.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/burdon/.npm/_logs/2023-11-04T18_19_39_512Z-debug-0.log
```

2). The scripts require directories to be built:

```zsh
▶ pnpm run preview

> think@0.1.0 preview /Users/burdon/Code/dxos/think
> vite preview

error when starting preview server:
Error: The directory "out/think" does not exist. Did you build your project?
    at preview (file:///Users/burdon/Code/dxos/think/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.8/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65641:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CAC.<anonymous> (file:///Users/burdon/Code/dxos/think/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.8/node_modules/vite/dist/node/cli.js:896:24)
 ELIFECYCLE  Command failed with exit code 1.
```

3). `serve` works but `preview` is broken:

```zsh
▶ pnpm run preview

> think@0.1.0 preview /Users/burdon/Code/dxos/think
> vite preview

  ➜  Local:   http://localhost:4173/
  ➜  Network: http://192.168.4.204:4173/

▶ curl http://localhost:4173/
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```

**Comment by zhenyasav** [comment]
wrong version of node being used likely

**Comment by richburdon** [comment]
Updated version note: https://github.com/dxos/dxos/commit/c2e07746fd828067110b3673d63d61305265490e
