### ISSUE TITLE
CLI error when resetting agent

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4750]
## 0). Space list always shows closed spaces (and no objects)

```
▶ dx space list
 key      open  name members objects epoch
 ──────── ───── ──── ─────── ─────── ─────
 044217e6 false      1       1       0
 0467a890 false      2       0       0
```

But diagnostics shows space has replicated:

```
▶ dx debug diagnostics --json --truncate
     {
        "key": "0467a890", <<========
        "metrics": {
          "open": "2023-11-21T17:48:10.098Z",
          "pipelineInitBegin": "2023-11-21T17:48:10.104Z",
          "controlPipelineReady": "2023-11-21T17:48:10.440Z",
          "dataPipelineOpen": "2023-11-21T17:48:10.463Z",
          "dataPipelineReady": "2023-11-21T17:48:10.473Z",
          "ready": "2023-11-21T17:48:10.473Z",
          "startupTime": 375
        },
        "db": {
          "objects": 4 <<========
        }
      }
```

## 1). Need to guard starting agent in foreground.

```
Code/dxos/dxos burdon/plugin-inbox-sync ✗                                                                                                                                           1h7m ⚑  ⍉
▶ LOG_FILTER="info" dx agent list
 profile process running locked restarts uptime
 ─────── ─────── ─────── ────── ──────── ──────────────────
 default 3104    true           0        less than a minute

Code/dxos/dxos burdon/plugin-inbox-sync ✗                                                                                                                                            1h7m ⚑
▶ LOG_FILTER="info" dx agent start
Warning: 'default' is already running.

Code/dxos/dxos burdon/plugin-inbox-sync ✗                                                                                                                                            1h7m ⚑
▶ LOG_FILTER="info" dx agent start -f
packages/core/agent/src/agent.ts:70 INFO Agent#0 using SimplePeer
Error: EAGAIN, Resource temporarily unavailable
```

## 2). Cannot reset space.

After attempting to reset -- identity already exists and previous spaces are still there.

```
[test-2] Code/dxos/dxos burdon/function-testbench ✗            6h19m ✖ ▴ ⚑ ✚
▶ dx agent stop && dx reset --no-agent --force && dx halo create $DX_PROFILE
Agent stopped
Starting agent (test-2)
Identity already initialized.

[test-2] Code/dxos/dxos burdon/function-testbench ✗            6h23m ✖ ▴ ⚑ ✚
▶ dx space list
 key      open  name members objects epoch
 ──────── ───── ──── ─────── ─────── ─────
 044693e7 false      1       1       0
 04c50bcd false      3       0       0
▶

```

## 3). Error when attempting to join existing space

```
[test-2] Code/dxos/dxos burdon/function-testbench ✗            6h18m ✖ ▴ ⚑ ✚
▶ dx space join

Invitation: https://composer.dxos.org?spaceInvitationCode=jLkgctdeCUwhbgP6PsYEBGEwKooOCvXfkjv6o1zaPjguh8Umq0W2TkRdmcQqXvDw2Tw7nKbtqVg4kIiwoeDl84DoPPsbyfvXGBNzvZg8NP6rHxT6tMaFgLXXH67Xx1IwTN6lyYiGfF8x2emkQSC7hQnaBRqLJSkXI8L9K4FiUryQ8osy0VpqQHgnABUqGSWzXvo2Dvri7lt9SNb4b78Rz9J9vrx5oz5WcOXhOdC1En9cg00r

Waiting for peer to connect... done

Secret: 150146
/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

SystemError: invariant violation: Space already exists. [!this._spaces.has(opts.spaceKey)] at packages/sdk/client-services/src/packlets/spaces/data-space-manager.ts:165
    at invariant (/Users/burdon/Code/dxos/dxos/packages/common/invariant/src/invariant.ts:37:9)
    at DataSpaceManager2.apply (/Users/burdon/Code/dxos/dxos/packages/sdk/client-services/src/packlets/spaces/data-space-manager.ts:165:5)
    at DataSpaceManager2.acceptSpace$synchronized (/Users/burdon/Code/dxos/dxos/packages/common/async/src/lock.ts:111:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SpaceInvitationProtocol.accept (/Users/burdon/Code/dxos/dxos/packages/sdk/client-services/src/packlets/invitations/space-invitation-protocol.ts:108:5)
    at /Users/burdon/Code/dxos/dxos/packages/sdk/client-services/src/packlets/invitations/invitations-handler.ts:320:30
    at runInContextAsync (/Users/burdon/Code/dxos/dxos/packages/common/async/src/task-scheduling.ts:54:5)
    at Timeout._onTimeout (/Users/burdon/Code/dxos/dxos/packages/common/async/src/task-scheduling.ts:77:5)
    at RPC dxos.client.services.InvitationsService.AcceptInvitation
    at PendingRpcRequest.resolve (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/rpc.ts:426:17)
    at RpcPeer._receive (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/rpc.ts:310:12)
    at cb (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/rpc.ts:140:20)
    at WebSocket._socket.onmessage (/Users/burdon/Code/dxos/dxos/packages/core/mesh/websocket-rpc/src/client.ts:38:15)
    at callListener (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/receiver.js:545:14)
    at Receiver.getData (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/receiver.js:478:17)
    at Receiver.startLoop (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/receiver.js:167:22)
    at Receiver._write (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/receiver.js:93:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Receiver.Writable.write (node:internal/streams/writable:337:10)
    at Socket.socketOnData (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/websocket.js:1286:35)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'Error',
  context: undefined
}
```

## PLEASE DISREGARD BELOW -- SEE NEXT COMMENT ##

Possible race condition when piping commands together? Cannot repro.

```
Code/dxos/dxos burdon/plugin-inbox-sync ✔                                                                                                                                           12h21m  ⍉
▶ dx reset --force --no-agent | dx halo create burdon-mbp
Starting agent (default)
ERROR Error: ENOENT: no such file or directory, open '/tmp/dx/run/profile/default/logs/daemon.log'
    at Object.openSync (node:fs:600:3)
    at writeFileSync (node:fs:2221:35)
    at WatchDog._log (/Users/burdon/Code/dxos/dxos/packages/common/phoenix/dist/lib/node/index.cjs:256:39)
    at WatchDog.start (/Users/burdon/Code/dxos/dxos/packages/common/phoenix/dist/lib/node/index.cjs:180:10)
    at WatchDog.start$synchronized (/Users/burdon/Code/dxos/dxos/packages/common/async/dist/lib/node/index.cjs:796:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Lock file is not being propagated with info.
    at waitForPidFileBeingFilledWithInfo (/Users/burdon/Code/dxos/dxos/packages/common/phoenix/src/utils.ts:30:12)
    at Function.start (/Users/burdon/Code/dxos/dxos/packages/common/phoenix/src/phoenix.ts:56:11)
    at PhoenixDaemon.start (/Users/burdon/Code/dxos/dxos/packages/core/agent/src/launcher/phoenix-daemon.ts:76:7)
    at /Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:302:21
    at Create.execWithDaemon (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:382:23)
    at Create.maybeStartDaemon (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:298:13)
    at Create.getClient (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:319:17)
    at Create.execWithClient (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:367:24)
    at Create.run (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/commands/halo/create.ts:32:16)
    at Create._run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/command.js:117:22)
    at Config.runCommand (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/config/config.js:329:25)
    at Object.run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/main.js:89:16)

Code/dxos/dxos burdon/plugin-inbox-sync ✔                                                                                                                                           12h22m  ⍉
▶ dx agent list
 profile process running locked restarts uptime
 ─────── ─────── ─────── ────── ──────── ──────

```

Should stop agent first.

```
▶ dx agent list
 profile process running locked restarts uptime
 ─────── ─────── ─────── ────── ──────── ──────────────────
 default 92358   true           0        less than a minute

Code/dxos/dxos burdon/plugin-inbox-sync ✔                                                                                                                                            12h23m
▶ dx reset --force --no-agent | dx halo create burdon-mbp
packages/core/mesh/websocket-rpc/src/client.ts:73 ERROR WebsocketRpcClient#0 connect ECONNREFUSED /tmp/dx/run/profile/default/agent.sock { url: 'ws+unix:///tmp/dx/run/profile/default/agent.sock' }
Error: connect ECONNREFUSED /tmp/dx/run/profile/default/agent.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

3). This error is 100% reproducible. But if you issue the commands separately, it 100% works, so likely a race condition and therefore needs more checks and error handling.

```
▶ dx agent stop | dx reset --force --no-agent | dx halo create burdon-mbp
Starting agent (default)
ERROR Error: ENOENT: no such file or directory, open '/tmp/dx/run/profile/default/logs/daemon.log'
    at Object.openSync (node:fs:600:3)
    at writeFileSync (node:fs:2221:35)
    at WatchDog._log (/Users/burdon/Code/dxos/dxos/packages/common/phoenix/dist/lib/node/index.cjs:256:39)
    at WatchDog.start (/Users/burdon/Code/dxos/dxos/packages/common/phoenix/dist/lib/node/index.cjs:180:10)
    at WatchDog.start$synchronized (/Users/burdon/Code/dxos/dxos/packages/common/async/dist/lib/node/index.cjs:796:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

...

Error: Lock file is not being propagated with info.
    at waitForPidFileBeingFilledWithInfo (/Users/burdon/Code/dxos/dxos/packages/common/phoenix/src/utils.ts:30:12)
    at Function.start (/Users/burdon/Code/dxos/dxos/packages/common/phoenix/src/phoenix.ts:56:11)
    at PhoenixDaemon.start (/Users/burdon/Code/dxos/dxos/packages/core/agent/src/launcher/phoenix-daemon.ts:76:7)
    at /Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:302:21
    at Create.execWithDaemon (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:382:23)
    at Create.maybeStartDaemon (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:298:13)
    at Create.getClient (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:319:17)
    at Create.execWithClient (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:367:24)
    at Create.run (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/commands/halo/create.ts:32:16)
    at Create._run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/command.js:117:22)
    at Config.runCommand (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/config/config.js:329:25)
    at Object.run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/main.js:89:16)

```

**Comment by nferch** [comment]
@richburdon what are you trying to accomplish piping the commands together? i don't see how the output is relevant to the next command, and none of them accept input from stdin. did you intend to use `&&` instead?

I've seen the 0) issue recently as well

**Comment by richburdon** [comment]
@nferch oh no. that's embarrassing -- yes i had meant `&&`. this was in my history for some reason and i just reused. thank you!

#0. probably needs to wait until the space is initialized.
