### ISSUE TITLE
Space join regression

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4898]
Console error when joining spaces.

```
Code/dxos/dxos burdon/plugin-mailbox ✗                     2d16h ⚑
▶ dx space join

Invitation: http://localhost:5173?spaceInvitationCode=jLjHenOZ2Nqr0zokGmTGR3NKxFK5p0r803FF4bSH6tghMy9LovD9saq1WZeL1CFnbSBRcbbYXcTFJtDfeyMZTJoU4EUnfxvtnJuYssl36qsmUgCYan2ZXJzesC0ZF0shs1dGmGfxDeh8vHwjbhYAI3RKMpS5IWKDEXGDryzppqCWTTJsgwO9dt52ei2N5Z2Slg03c9l9PC2GxHxPEvPUy6P1bnOMTgjgNLhMo0ymp1Vni3uc

Waiting for peer to connect... done

Secret: 533013

Joined successfully.
packages/core/echo/echo-schema/src/automerge/automerge-context.ts:72 ERROR LocalClientNetworkAdapter#0 RPC_CLOSED: Request was terminated because the RPC endpoint is closed.
    at RpcPeer._abortRequests (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/rpc.ts:233:18)
    at RpcPeer.close (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/rpc.ts:193:10)
    at ProtoRpcPeer.close (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/service.ts:43:22)
    at WebsocketRpcClient.close (/Users/burdon/Code/dxos/dxos/packages/core/mesh/websocket-rpc/src/client.ts:84:24)
    at AgentClientServiceProvider.close (/Users/burdon/Code/dxos/dxos/packages/sdk/client/src/services/agent.ts:61:27)
    at Client.destroy (/Users/burdon/Code/dxos/dxos/packages/sdk/client/src/client/client.ts:319:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Client.destroy$synchronized (/Users/burdon/Code/dxos/dxos/packages/common/async/src/lock.ts:111:14)
    at Join.execWithClient (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:374:9)
    at Join.run (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/commands/space/join.ts:39:16)
    at Join._run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/command.js:117:22)
    at Config.runCommand (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/config/config.js:329:25)
    at Object.run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/main.js:89:16)

Error happened in the stream at:
    at producer (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/rpc.ts:434:21)
    at new _Stream (/Users/burdon/Code/dxos/dxos/packages/common/codec-protobuf/src/stream.ts:198:31)
    at RpcPeer.callStream (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/rpc.ts:418:12)
    at Object.callStream (/Users/burdon/Code/dxos/dxos/packages/core/mesh/rpc/src/service.ts:132:54)
    at Service.syncRepo (/Users/burdon/Code/dxos/dxos/packages/common/codec-protobuf/src/service.ts:71:34)
    at LocalClientNetworkAdapter.connect (/Users/burdon/Code/dxos/dxos/packages/core/echo/echo-schema/src/automerge/automerge-context.ts:63:38)
    at NetworkSubsystem.addNetworkAdapter (/Users/burdon/Code/dxos/dxos/packages/core/echo/automerge/dist/lib/node/automerge-repo.cjs:578:20)
    at /Users/burdon/Code/dxos/dxos/packages/core/echo/automerge/dist/lib/node/automerge-repo.cjs:531:34
    at Array.forEach (<anonymous>)
    at new NetworkSubsystem (/Users/burdon/Code/dxos/dxos/packages/core/echo/automerge/dist/lib/node/automerge-repo.cjs:531:14)
    at new Repo (/Users/burdon/Code/dxos/dxos/packages/core/echo/automerge/dist/lib/node/automerge-repo.cjs:1282:30)
    at new AutomergeContext (/Users/burdon/Code/dxos/dxos/packages/core/echo/echo-schema/src/automerge/automerge-context.ts:20:18)
    at new SpaceList (/Users/burdon/Code/dxos/dxos/packages/sdk/client/src/echo/space-list.ts:64:30)
    at Client.initialize (/Users/burdon/Code/dxos/dxos/packages/sdk/client/src/client/client.ts:249:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Client.initialize$synchronized (/Users/burdon/Code/dxos/dxos/packages/common/async/src/lock.ts:111:14)
    at Join.getClient (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:328:13)
    at Join.execWithClient (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:368:24)
    at Join.run (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/commands/space/join.ts:39:16)
    at Join._run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/command.js:117:22)
    at Config.runCommand (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/config/config.js:329:25)
    at Object.run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_@swc+core@1.3.70_@types+node@18.11.9_typescript@5.2.2/node_modules/@oclif/core/lib/main.js:89:16)

```

**Comment by mykola-vrmchk** [comment]
Thanks, for reporting it, it is automerge sync failure after the client is closed so no worries it does not cause any issues except an ugly error message in the console.

I will fix it. We need to close the connection gracefully.

**Comment by mykola-vrmchk** [comment]
https://github.com/dxos/dxos/pull/4899
