### ISSUE TITLE
[cli] `dx halo identity` throws error when agent is running

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4928]
- Start a new agent
- Run `dx halo identity`

```bash
% DX_PROFILE=test dx agent start --ws=4567
Agent started.
% dx agent list
 profile process running locked restarts uptime
 ─────── ─────── ─────── ────── ──────── ──────────────────
 default         true                    Null
 test    15728   true           0        less than a minute
% DX_PROFILE=test dx halo identity
Identity key: 046808ed96cf1444047e7a3ccb5428d7759c6b22417ad097fea92b9e1cd91183f13054944932d68ed1d56f0d24bc38dc534ce1b5317133227034300022f6ea6387
Display name: undefined
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: invariant violation: No identity. Default space is created with an identity. [identityKey] at packages/sdk/client/src/echo/space-list.ts:197
    at invariant (/Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/@dxos/invariant/dist/lib/node/index.cjs:40:9)
    at get default [as default] (/Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/@dxos/client/dist/lib/node/chunk-GXJ46TDK.cjs:886:36)
    at Object.next (/Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/@dxos/client/dist/lib/node/chunk-GXJ46TDK.cjs:848:74)
    at notifySubscription (/Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/zen-observable/lib/Observable.js:117:18)
    at onNotify (/Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/zen-observable/lib/Observable.js:159:3)
    at Object.next (/Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/zen-observable/lib/Observable.js:177:9)
    at /Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/@dxos/async/dist/lib/node/index.cjs:598:62
    at Set.forEach (<anonymous>)
    at Object.next (/Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/@dxos/async/dist/lib/node/index.cjs:598:25)
    at notifySubscription (/Users/jessmartin/.asdf/installs/nodejs/18.14.2/lib/node_modules/@dxos/cli/node_modules/zen-push/node_modules/zen-observable/lib/Observable.js:121:18)
```

**Comment by nferch** [comment]
I cannot repro this on c414ce052. where in your usage did you create an identity?

**Comment by jessmartin** [comment]
> I cannot repro this on [c414ce0](https://github.com/dxos/dxos/commit/c414ce05257cbc4a6e2d2b9705043b70b3fc370f).

Ah, I'm on `0.3.9-next.35264cb`. Will try what newest on `main` and see what happens.

**Comment by jessmartin** [comment]
This appears to be fixed on main. Closing.
