### ISSUE TITLE
[composer] stacks broken

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4962]
- create a stack
- add a document to it
- it fails to render

error in console:
```
TypeError: i.text is not a function
    at index.mjs:745:1
    at ol (react-dom.production.min.js:244:1)
    at Gn (react-dom.production.min.js:286:1)
    at ad (react-dom.production.min.js:283:1)
    at gn (react-dom.production.min.js:281:1)
    at Fi (react-dom.production.min.js:273:1)
    at mn (react-dom.production.min.js:127:1)
    at ad (react-dom.production.min.js:283:1)
    at gn (react-dom.production.min.js:281:1)
    at Aa (react-dom.production.min.js:270:1)
```

**Comment by jessmartin** [comment]
Looks like this got fixed.
