### ISSUE TITLE
[native] app crashes and won't restart after resetting identity

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5441]
## Repro
- HALO > Reset > Blank screen
- Right-click > Reload
- Hangs for 30s

```
NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```

```
no agent hosting configured
no agent hosting configured
no agent hosting configured
no agent hosting configured
%cAa#0 color:#C026D3;font-weight:bold Erasing all data...
%cAa#0 color:#C026D3;font-weight:bold @socket://org.dxos.composer/assets/index-dA5WYrOf.js:1:44433
TypeError: null is not an object (evaluating 'a.identityKey')
    at (assets/index-GTeehxqH.js:1:9200)
    at map [native code]
    at q (assets/index-GTeehxqH.js:1:9147)
    at ql (assets/react-zH1MIoXm.js:30:19479)
    at no (assets/react-zH1MIoXm.js:32:3136)
    at Vs (assets/react-zH1MIoXm.js:32:39501)
    at cd (assets/react-zH1MIoXm.js:32:39432)
    at la (assets/react-zH1MIoXm.js:32:39291)
    at vo (assets/react-zH1MIoXm.js:32:35712)
    at Fs (assets/react-zH1MIoXm.js:32:36513)
    at lt (assets/react-zH1MIoXm.js:30:3259)
    at (assets/react-zH1MIoXm.js:32:34062)
%cDatabaseProxy#0 color:#C026D3;font-weight:bold timeout waiting for mutations to flush { timeout: 5000, mutationTags: [] }
%cDatabaseProxy#1 color:#C026D3;font-weight:bold timeout waiting for mutations to flush { timeout: 5000, mutationTags: [] }
no agent hosting configured
Error: invariant violation: HaloProxy not opened [this._invitationProxy] at packages/sdk/client/src/halo/halo-proxy.ts:86
    at InvariantViolation (assets/dxos-UaynLrIH.js:13:33982)
    at invariant (assets/dxos-UaynLrIH.js:13:33918)
    at invitations (assets/halo-1XoNpGBi.js:1:1573)
    at (assets/chunk-UC2HPP2Z-Hy-L2Qun.js:1:837)
    at ji (assets/react-zH1MIoXm.js:30:21577)
    at a (assets/chunk-UC2HPP2Z-Hy-L2Qun.js:1:749)
    at to (assets/shell-KajqWLRH.js:3:45529)
    at ql (assets/react-zH1MIoXm.js:30:19479)
    at no (assets/react-zH1MIoXm.js:32:3136)
    at Vs (assets/react-zH1MIoXm.js:32:39501)
    at cd (assets/react-zH1MIoXm.js:32:39432)
    at la (assets/react-zH1MIoXm.js:32:39291)
    at vo (assets/react-zH1MIoXm.js:32:35712)
    at Fs (assets/react-zH1MIoXm.js:32:36513)
    at lt (assets/react-zH1MIoXm.js:30:3259)
    at (assets/react-zH1MIoXm.js:32:34062)
%cDatabaseProxy#0 color:#C026D3;font-weight:bold timeout waiting for mutations to flush { timeout: 5000, mutationTags: [] }
%cDatabaseProxy#1 color:#C026D3;font-weight:bold timeout waiting for mutations to flush { timeout: 5000, mutationTags: [] }
```

**Comment by wittjosiah** [comment]
- the reset failure seems specific to monolithic mode in webkit
- worker services do work in socket, but not in production bundle, only in dev mode
