### ISSUE TITLE
[composer] cycle detected in app graph when creating a stack

### ISSUE THREAD

**Issue by yarolegovich** [dxos/dxos#5844]
On the main branch when I:
1. Open an incognito tab.
2. Add a new space.
3. Add a stack in it.
4. Create another space.
In the console I get:
```
chunk-TEUXL7NL.js?v=1a400c5e:44 Uncaught Error: Cycle detected
    at i (chunk-FKNXQLNG.js?v=1a400c5e:3:9)
    at d.set (chunk-FKNXQLNG.js?v=1a400c5e:161:7)
    at Object.set (deepsignal_react.js?v=1a400c5e:209:38)
    at graph.ts:151:26
    at s (chunk-FKNXQLNG.js?v=1a400c5e:55:12)
    at Graph._addNode (graph.ts:149:12)
    at graph.ts:141:37
    at Array.map (<anonymous>)
    at Graph.addNodes (graph.ts:141:18)
    at StackPlugin.tsx:108:34
```
Add the newly created space doesn't have a "+" for adding elements in it.

<img width="287" alt="image" src="https://github.com/dxos/dxos/assets/9644546/58354cbb-d17c-45f1-845b-e56c5d604299">

**Comment by wittjosiah** [comment]
Unable to reproduce on `main`, may be resolved. Closing for now.
