### ISSUE TITLE
[agent] file logging fails with EAGAIN

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#6227]
stdout/stderr are sometimes non-blocking: https://github.com/nodejs/node/issues/42826

```Error: EAGAIN: resource temporarily unavailable, write
    at Object.writeSync (node:fs:929:3)
    at Object.writeFileSync (node:fs:2328:26)
    at appendFileSync (node:fs:2384:6)
    at /prod/cli/node_modules/.pnpm/file+packages+common+log/node_modules/@dxos/log/dist/lib/node/index.cjs:425:40
    at /prod/cli/node_modules/.pnpm/file+packages+common+log/node_modules/@dxos/log/dist/lib/node/index.cjs:516:52
    at Array.forEach (<anonymous>)
    at processLog (/prod/cli/node_modules/.pnpm/file+packages+common+log/node_modules/@dxos/log/dist/lib/node/index.cjs:516:29)
    at log2.info (/prod/cli/node_modules/.pnpm/file+packages+common+log/node_modules/@dxos/log/dist/lib/node/index.cjs:507:30)
    at ProtocolStream.<anonymous> (/prod/cli/node_modules/.pnpm/file+packages+core+mesh+teleport-extension-replicator/node_modules/@
dxos/teleport-extension-replicator/dist/lib/node/index.cjs:389:22)
    at ProtocolStream.emit (node:events:529:35) {
  errno: -11,
  syscall: 'write',
  code: 'EAGAIN'
}```

**Comment by nferch** [comment]
to repro:

```
package main

import (
        "log"
        "os"
        "os/exec"
)

func main() {

        cmd := exec.Command("node", "bin/dev", "agent", "start", "-f", "--json-log", "--verbose")
        cmd.Env = append(os.Environ(), "LOG_FILTER=debug", "JSON_LOG_FILTER=debug", "DX_PROFILE=agent-device-test4")

        cmd.Stdout = os.Stdout
        //cmd.Stderr = os.Stderr

        _, err := cmd.StderrPipe()
        if err != nil {
                panic(err)
        }

        err = cmd.Start()
        if err != nil {
                panic(err)
        }

        err = cmd.Wait()
        if err != nil {
                log.Printf("Command finished with error: %v", err)
        }
}```

may need to run a few commands like `halo identity` to generate enough log output
