### ISSUE TITLE
RPC_CLOSED error with agent

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#6472]
Repro:

Start agent in another terminal

```

>DX_PROFILE=agent-rpc-closed bin/dev halo create foo

>DX_PROFILE=agent-rpc-closed bin/dev halo identity
Identity key: 042c265473fdb2b02fa3d32c19e3d3a98392254ab5f6046a2f0047cedc313b737e7a607e9b890c63fbd3e18df733bf6a31425a726203ec722ad5042d16a3069693
Display name: foo
packages/core/echo/echo-db/src/automerge/automerge-context.ts:202 ERROR LocalClientNetworkAdapter#0 Request was terminated because the RPC endpoint is closed. {
  error: RPC_CLOSED: Request was terminated because the RPC endpoint is closed.
      at RpcPeer.call (/Users/nf/work/dxos-clean/packages/core/mesh/rpc/src/rpc.ts:396:23)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Service.sendSyncMessage (/Users/nf/work/dxos-clean/packages/common/codec-protobuf/src/service.ts:84:28)

   info: RPC client was closed at:
      at RpcPeer._abortRequests (/Users/nf/work/dxos-clean/packages/core/mesh/rpc/src/rpc.ts:237:18)
      at RpcPeer.close (/Users/nf/work/dxos-clean/packages/core/mesh/rpc/src/rpc.ts:197:10)
      at ProtoRpcPeer.close (/Users/nf/work/dxos-clean/packages/core/mesh/rpc/src/service.ts:45:22)
      at WebsocketRpcClient.close (/Users/nf/work/dxos-clean/packages/core/mesh/websocket-rpc/src/client.ts:91:24)
      at AgentClientServiceProvider.close (/Users/nf/work/dxos-clean/packages/sdk/client/src/services/agent.ts:70:27)
      at Client._close (/Users/nf/work/dxos-clean/packages/sdk/client/src/client/client.ts:470:27)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Client.destroy (/Users/nf/work/dxos-clean/packages/sdk/client/src/client/client.ts:457:5)
      at async Client.destroy$synchronized (/Users/nf/work/dxos-clean/packages/common/async/src/mutex.ts:129:14)
      at async Identity.execWithClient (/Users/nf/work/dxos-clean/packages/devtools/cli/src/base-command.ts:497:5) {
    code: 'RPC_CLOSED',
    context: undefined
  }
} RPC_CLOSED: Request was terminated because the RPC endpoint is closed.
packages/core/echo/echo-db/src/automerge/automerge-context.ts:202 ERROR LocalClientNetworkAdapter#0 Request was terminated because the RPC endpoint is closed. {
  error: RPC_CLOSED: Request was terminated because the RPC endpoint is closed.
      at RpcPeer.call (/Users/nf/work/dxos-clean/packages/core/mesh/rpc/src/rpc.ts:396:23)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Service.sendSyncMessage (/Users/nf/work/dxos-clean/packages/common/codec-protobuf/src/service.ts:84:28)

   info: RPC client was closed at:
      at RpcPeer._abortRequests (/Users/nf/work/dxos-clean/packages/core/mesh/rpc/src/rpc.ts:237:18)
      at RpcPeer.close (/Users/nf/work/dxos-clean/packages/core/mesh/rpc/src/rpc.ts:197:10)
      at ProtoRpcPeer.close (/Users/nf/work/dxos-clean/packages/core/mesh/rpc/src/service.ts:45:22)
      at WebsocketRpcClient.close (/Users/nf/work/dxos-clean/packages/core/mesh/websocket-rpc/src/client.ts:91:24)
      at AgentClientServiceProvider.close (/Users/nf/work/dxos-clean/packages/sdk/client/src/services/agent.ts:70:27)
      at Client._close (/Users/nf/work/dxos-clean/packages/sdk/client/src/client/client.ts:470:27)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Client.destroy (/Users/nf/work/dxos-clean/packages/sdk/client/src/client/client.ts:457:5)
      at async Client.destroy$synchronized (/Users/nf/work/dxos-clean/packages/common/async/src/mutex.ts:129:14)
      at async Identity.execWithClient (/Users/nf/work/dxos-clean/packages/devtools/cli/src/base-command.ts:497:5) {
    code: 'RPC_CLOSED',
    context: undefined
  }
} RPC_CLOSED: Request was terminated because the RPC endpoint is closed.
```

**Comment by richburdon** [comment]
Adding logic to ignore warning if closing/shutting down.
