### ISSUE TITLE
[tables] error dragging table between spaces

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7764]
```
invariant.ts:43 Uncaught (in promise) InvariantViolation: invariant violation: No serializer for type: dxos.org/type/Table [serializer] at packages/plugins/plugin-space/src/util.tsx:639
    at invariant (http://localhost:5173/@fs/Users/ian/code/dxos/packages/common/invariant/dist/lib/browser/index.mjs:19:9)
    at cloneObject (http://localhost:5173/@fs/Users/ian/code/dxos/packages/plugins/plugin-space/src/util.tsx:695:5)
    at Proxy.onCopy (http://localhost:5173/@fs/Users/ian/code/dxos/packages/plugins/plugin-space/src/util.tsx:104:37)
    at Object.onDrop (http://localhost:5173/@fs/Users/ian/code/dxos/packages/plugins/plugin-navtree/src/components/NavTreeContainer.tsx:269:63)
    at handleDragEnd (http://localhost:5173/@fs/Users/ian/code/dxos/packages/ui/react-ui-mosaic/src/mosaic/Root.tsx:184:61)
    at http://localhost:5173/node_modules/.vite/deps/chunk-CU6M74PO.js?v=46e660ac:2719:43
    at batchedUpdates$1 (http://localhost:5173/node_modules/.vite/deps/chunk-EP455A3S.js?v=46e660ac:18881:20)
    at handler (http://localhost:5173/node_modules/.vite/deps/chunk-CU6M74PO.js?v=46e660ac:2708:56)
```

**Comment by seagreen** [comment]
I feel like this might be a duplicate, but I couldn't find the earlier issue.
